### ISSUE TITLE
missing LICENSE file

### ISSUE THREAD

**Issue by rudolfolah** [tolicodes/node-api-toolkit#1]
in the package.json the LICENSE is listed as the ISC. I would recommend the [GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) or [MIT licenses](https://opensource.org/licenses/MIT).

**Comment by tolicodes** [comment]
Thanks! Added the Unlicense (free to do whatever with no restrictions whatsoever). If someone wants to steal it as their own and sell it, I'll take it as a compliment :D
